# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['auto_switch_server.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['psutil', 'netifaces'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter', 'tkinter.*',
        'turtle',
        'unittest', 'unittest.*',
        'test', 'test.*',
        'doctest',
        'pdb', 'pdb.*',
        'cProfile',
        'profile',
        'pstats',
        'PyQt4', 'PyQt5', 'PyQt6',
        'PySide', 'PySide2', 'PySide6',
        'wx', 'wx.*',
        'numpy', 'numpy.*',
        'scipy', 'scipy.*',
        'matplotlib', 'matplotlib.*',
        'pandas', 'pandas.*',
    ],
    noarchive=False,
    optimize=1,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=None, optimize=1)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='auto_switch_server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['swap.ico'],
    onefile=True,
)
